name: oms
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #packages
  intl: ^0.18.0
  get: ^4.6.1
  get_storage: ^2.0.3
  iconly: ^1.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.4.0
  animate_do: ^3.0.2
  cached_network_image: ^3.2.0
  derry: ^1.4.3
  carousel_slider: ^4.0.0
  zoom_tap_animation: ^1.1.0
  flutter_svg: ^2.0.5
  equatable: ^2.0.5
  data_table_2:
    path: ./dependencies/data_table_2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  freezed: ^2.3.2
  json_serializable: ^6.1.5


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/fonts/
    - assets/fonts/PlusJakartaSans/
    - assets/images/menu/
    - assets/images/home/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700

scripts: derry.yaml